import { Block } from "baseui/block";
import Head from "next/head";
import { useRouter } from "next/router";
import { ClientsHomePage } from "../../components/incidents/client-incident-view/ClientHomePage";
import {
  ERROR_PAGE_OVERRIDES,
  MAIN_STYLE_OVERRIDES,
} from "../../components/incidents/internal/form/overrides/BlockOverrides";
import { PAGE_NAME } from "../../constants";

const ClientsPage: React.FC = (props) => {
  return (
    <>
      <Head>
        <title>{PAGE_NAME} Status</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/titleIcon.png" />
      </Head>
      <ClientsHomePage />;
    </>
  );
};

const WrongUrlPage = () => {
  return (
    <Block overrides={{ ...MAIN_STYLE_OVERRIDES }}>
      <Block overrides={{ ...ERROR_PAGE_OVERRIDES }}>
        <h1 className="header">
          Sorry the Page you requested for is not available!!!
        </h1>
        <Block></Block>
      </Block>
    </Block>
  );
};

export default () => {
  const router = useRouter();

  let content: React.ReactElement = <></>;

  const { params = [] } = router.query;
  if (params.length === 0) {
    content = <ClientsPage />;
  } else {
    content = <WrongUrlPage />;
  }

  return content;
};
