// lib
import { useSession } from "next-auth/react";
import Head from "next/head";

// components
import { Block } from "baseui/block";
import { Spinner } from "baseui/spinner";
import WelcomePage from "../components/WelcomePage/WelcomePage";
import LandingPage from "../components/landingPage/LandingPage";

// styles
import { hasListLoadedStyle } from "../components/incidents/list/overrides/listStyles";

const Home = () => {
  const { data: session, status } = useSession(); // get user's session details

  // if status not confirmed
  if (status === "loading") {
    return (
      <Block {...hasListLoadedStyle}>
        <Spinner />
      </Block>
    );
  }

  // is user not logged in redirect to welcome page
  if (!session) return <WelcomePage />;

  // if logged in, take to Landing Page
  return (
    <>
      <Head>
        <title>statusapp</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Status_icon.png" />
      </Head>
      <LandingPage />
    </>
  );
};

export default Home;
