import { Block } from "baseui/block";
import { StatefulMenu } from "baseui/menu";
import Head from "next/head";
import Router from "next/router";
import { Avatar } from "baseui/avatar";
import { Spinner } from "baseui/spinner";
import { hasListLoadedStyle } from "../components/incidents/incidents-list-view/styles/listStyles";
import { useSession } from "next-auth/react";
import WelcomePage from "../components/welcome/WelcomePage";
import LandingPage from "../components/component/LandingPage/LandingPage";

let numberofLoads: number = 0;

const Home = () => {
  const { data: session, status } = useSession();
  if (status === "loading") {
    numberofLoads++;
    return (
      <Block {...hasListLoadedStyle}>
        <Spinner />
      </Block>
    );
  }
  if (!session) {
    return <WelcomePage />;
  }
  return (
    <>
      <Head>
        <title>Status App</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&display=swap"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Status_icon.png" />
      </Head>
      <LandingPage />
    </>
  );
};

export default Home;
